### ISSUE TITLE
Infrastructure Training

### ISSUE THREAD

**Issue by xmunoz** [PermanentOrg/infrastructure#29]
I will be delivering an infrastructure training on Dec 28, focusing on all of the new tools that I've developed for Permanent. Please comment in this issue to let me know which specific issue areas that you'd like covered. Some examples:

- Networking Basics
- Ansible vs bash for configuration management
- How deployment works
- Docker and our CI tests
- Which tools are responsible for what (e.g. image building, code deployment, infra deployment)
- How Terraform works
- Making changes to the local development environment only
- Making changes to the AWS environment only
- How secrets are used and where they are stored
- The what, where, when, how and why of tests

**Comment by cecilia-donnelly** [comment]
Not exactly "infrastructure" but I'd love to talk about the Wordpress->Squarespace transition and any hidden wrinkles we might run into in that process.

**Comment by xmunoz** [comment]
I'm not a Wordpress expert by any stretch of the imagination, but I can talk about how it's integrated with the rest of the system.

**Comment by cecilia-donnelly** [comment]
Thanks!  I also notice we have a Jira ticket about a Docker training - are you imagining that we'll wrap that in here?  (I see you have "Docker and our CI tests" on this list.)

**Comment by xmunoz** [comment]
I will cover a little bit about Docker. I recommend getting up to speed with the basics though before the training: https://docs.docker.com/get-started/overview/

**Comment by cecilia-donnelly** [comment]
Notes from this training: https://github.com/PermanentOrg/meta/blob/master/meetings/2020-12-28-infra-training.md
