### ISSUE TITLE
Upgrade terraform version

### ISSUE THREAD

**Issue by xmunoz** [PermanentOrg/infrastructure#74]
![Captura de pantalla de 2021-10-20 16-09-39](https://user-images.githubusercontent.com/1065196/138172536-b524571d-0860-422f-b83f-af61b85cb247.png)

The version of terraform that we're using  on Terraform cloud has not been upgraded since I set it up last year.

**Comment by xmunoz** [comment]
Everything is on 1.0.11 now. Will wait until after the next release before closing this issue.

**Comment by xmunoz** [comment]
Looks like terraform apply just completed for the most recent release. Since it's now running the latest version, this is fixed!

**Comment by jasonaowen** [comment]
Nice work, @xmunoz!
