### ISSUE TITLE
Support Sentry for upload-config

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/infrastructure#9]
#### Description
The upload-config repository requires two environment variables (`SENTRY_ENVIRONMENT` and `SENTRY_DSN`) in order to support Sentry.  We need to update the service definition to provide those vars.

**Comment by xmunoz** [comment]
The environment should be configured in the build script, but I believe that the DSN can be a repository-level variable.

**Comment by xmunoz** [comment]
Changed my mind about the above. A modified service config is fine.
